// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYUV1OtNqEHT5RWKFFCrwKVRSNwhmNJsc',
    appId: '1:536681349166:web:c54ba3f4d436d94037dfbf',
    messagingSenderId: '536681349166',
    projectId: 'airsoft-mobile-store',
    authDomain: 'airsoft-mobile-store.firebaseapp.com',
    storageBucket: 'airsoft-mobile-store.firebasestorage.app',
    measurementId: 'G-QX41NVZ8W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVN-hdU93Rwo8moEGdkEQnSfGAdzPLfwM',
    appId: '1:536681349166:android:c11c31ff9eb57eb137dfbf',
    messagingSenderId: '536681349166',
    projectId: 'airsoft-mobile-store',
    storageBucket: 'airsoft-mobile-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRv8dAtFOGu51_eXLPbox0Q58gwJybvoM',
    appId: '1:536681349166:ios:7fadb192e9424f3837dfbf',
    messagingSenderId: '536681349166',
    projectId: 'airsoft-mobile-store',
    storageBucket: 'airsoft-mobile-store.firebasestorage.app',
    iosBundleId: 'com.example.airsoftShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRv8dAtFOGu51_eXLPbox0Q58gwJybvoM',
    appId: '1:536681349166:ios:7fadb192e9424f3837dfbf',
    messagingSenderId: '536681349166',
    projectId: 'airsoft-mobile-store',
    storageBucket: 'airsoft-mobile-store.firebasestorage.app',
    iosBundleId: 'com.example.airsoftShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYUV1OtNqEHT5RWKFFCrwKVRSNwhmNJsc',
    appId: '1:536681349166:web:755047b65d4382fc37dfbf',
    messagingSenderId: '536681349166',
    projectId: 'airsoft-mobile-store',
    authDomain: 'airsoft-mobile-store.firebaseapp.com',
    storageBucket: 'airsoft-mobile-store.firebasestorage.app',
    measurementId: 'G-H89PY20RNV',
  );
}
